name: Build Action Dist
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Update Repo
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git status
          git add dist
          git commit -m ":construction_worker: CI Dist Update"
          git push
