name: Build Action Dist
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Check Status
        run: git status
      - name: Add Files
        run: git add dist
      - name: Commit
        run: git commit -m ":construction_worker: CI Dist Update"
      - name: Push
        run: git push
